title = "Job-1"

[mesh]
type = "gmsh"
file = "rectangle4.msh"

[dof]
names = ["u1", "u2", "phi"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['bottom']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['left']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['top']
value = 0.1

[solver]
#type = "LinearSolver"
type = "NonlinearSolver"
option = "NewtonRaphson"
total_time = 1.0
max_increment = 1000000
initial_dtime = 0.1
max_dtime = 1.0
min_dtime = 0.001

#[[materials]]
#name = "Material-1"
#category = "Elastic"
#type = "Isotropic"
#data = [1.0e5, 0.25]

[[materials]]
name = "Material-1"
category = "Plastic"
type = "KinematicHardening"
data = [100000.0, 0.25, 400.0, 1000.0]

[[materials]]
name = "Material-2"
category = "PhaseField"
type = "Damage"
data = [1.0, 1.0]

[[materials]]
name = "Material-3"
category = "SolidThermal"
type = "Expansion"
data = [1.0e-3]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "SolidPhaseFieldDamage"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["rectangle"]
material_names = ["Material-1", "Material-2"]
data = []

[[outputs]]
type = "vtk"
field_outputs = ['S11', 'S22', 'S12', 'E11', 'E22', 'E12']
on_screen = false
