title = "Job-1"

[mesh]
type = "abaqus"
file = "CT_3D.inp"

[dof]
names = ["u1", "u2", "u3", "phi"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ["NSET-Y0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ["NSET-Y1"]
element_sets = []
value = 1.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u3"]
node_sets = ["NSET-Z0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ["NSET-X0Y0"]
element_sets = []
value = 0.8

[solver]
type = "NonlinearSolver"
option = "NR"
total_time = 1.0
start_time = 0.0
max_increment = 10000000
initial_dtime = 0.01
max_dtime = 0.01
min_dtime = 0.00001

[[materials]]
name = "Material-1"
category = "Elastic"
type = "Isotropic"
data = [112500, 0.34]

[[materials]]
name = "Material-2"
category = "PhaseField"
type = "Damage"
data = [0.1, 0.0001]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "SolidPhaseDamage"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["ESET-ALL"]
material_names = ["Material-1", "Material-2"]
data = []

[[outputs]]
type = "vtk"
field_outputs = ["S11", "S22", "S33", "S12","S13","S23", "E11", "E22", "E33", "E12", "E13", "E23", "Energy"]
is_save = true

[[outputs]]
type = "text"
is_save = true
