title = "Job-1"

[mesh]
type = "abaqus"
file = "rectangle_hole_quad4.inp"

[dof]
names = ["u1", "u2"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u1", "u2"]
node_sets = ["Set-0", "Set-11"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "NeumannBC"
type = "Concentrated"
dof = ["u2"]
node_sets = ["Set-21"]
element_sets = []
value = 2000.0

#[[bcs]]
#name = "BC-3"
#category = "DirichletBC"
#type = ""
#dof = ["u2"]
#node_sets = ["Set-21"]
#element_sets = []
#value = 1.0

[solver]
type = "NonlinearSolver"
option = "NR"
total_time = 1.0
start_time = 0.0
max_increment = 10000
initial_dtime = 0.01
max_dtime = 1.0
min_dtime = 1e-6

[[materials]]
name = "Material-1"
category = "Plastic"
type = "KinematicHardening"
data = [100000.0, 0.25, 400.0, 1000.0]

[[materials]]
name = "Material-2"
category = "Elastic"
type = "Isotropic"
data = [1.0e6, 0.25]

[[sections]]
name = "Section-1"
category = "Solid"
type = "PlaneStrain"
option = "FiniteStrain"
element_sets = ["Set-All"]
material_names = ["Material-2"]
data = []

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[outputs]]
type = "vtk"
field_outputs = ["S11", "S22", "S12", "E11", "E22", "E12"]
is_save = true
