title = "Job-1"

[mesh]
type = "abaqus"
file = "particle.inp"

[dof]
names = ["u1", "u2", "phi"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['X0Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['Y1']
element_sets = []
value = 0.05

[solver]
type = "NonlinearSolver"
option = "NR"
total_time = 1.0
start_time = 0.0
max_increment = 100
initial_dtime = 0.1
max_dtime = 1.0
min_dtime = 0.001

[[materials]]
name = "Material-1"
category = "Elastic"
type = "Isotropic"
data = [1.0e5, 0.25]

[[materials]]
name = "Material-2"
category = "PhaseField"
type = "Damage"
data = [1.0, 0.005]

[[materials]]
name = "Material-3"
category = "PhaseField"
type = "Damage"
data = [1000.0, 0.005]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "SolidPhaseDamage"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["ELSET_MATRIX", "ELSET_INTERFACES"]
material_names = ["Material-1", "Material-2"]
data = []

[[sections]]
name = "Section-2"
category = "SolidPhaseDamage"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["ELSET_PARTICLES"]
material_names = ["Material-1", "Material-3"]
data = []

[[outputs]]
type = "vtk"
field_outputs = ['S11', 'S22', 'S12', 'E11', 'E22', 'E12']
is_save = true
