title = "Job-1"

[mesh]
type = "gmsh"
#file = 'rectangle4.msh'
#file = 'rectangle9.msh'
file = 'rectangle100.msh'
#file = 'rectangle10000.msh'
#file = 'quad100.msh'
#file = 'quad40000.msh'
#file = 'quad160000.msh'
#file = 'quad_tria3.msh'

[dof]
names = ["u1", "u2"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
type = "DirichletBC"
dof = ["u2"]
node_sets = ['bottom']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
type = "DirichletBC"
dof = ["u1"]
node_sets = ['left']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
type = "DirichletBC"
dof = ["u2"]
node_sets = ['top']
element_sets = []
value = 0.01

[solver]
type = "NonlinearSolver"
#type = "LinearSolver"

[[materials]]
name = "Material-1"
category = "Plastic"
type = "KinematicHardening"
data = [100000.0, 0.25, 400.0, 1000.0]

[[materials]]
name = "Material-2"
category = "Elastic"
type = "Isotropic"
data = [1.0e5, 0.25]

[[sections]]
name = "Section-1"
category = "Solid"
type = "PlaneStress"
option = "SmallStrain"
element_sets = ["rectangle"]
material_name = "Material-1"
data = []

[[outputs]]
type = "vtk"
field_outputs = ['S11', 'S22', 'S12', 'E11', 'E22', 'E12']
on_screen = false

[[outputs]]
type = "text"
on_screen = false
