title = "Job-1"

[mesh]
type = "gmsh"
#file = 'F:\Github\pyfem\examples\rectangle\rectangle.msh'
#file = 'F:\Github\pyfem\examples\rectangle\rectangle10000.msh'
file = 'F:\Github\pyfem\examples\rectangle\quad.msh'
#file = 'F:\Github\pyfem\examples\rectangle\quad160000.msh'
#file = 'F:\Github\pyfem\examples\rectangle\quad40000.msh'
#file = 'F:\Github\pyfem\examples\rectangle\quad_tria3.msh'

[dof]
names = ["u1", "u2"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
type = "DirichletBC"
dof = ["u1"]
node_sets = ['bottom'] # This must match a named boundary in the mesh file
element_sets = [] # This must match a named boundary in the mesh file
value = 0.0

[solver]
type = "LinearSolver"

[[materials]]
name = "Material-1"
category = "Elastic"
type = "Isotropic"
data = [1.0e5, 0.25]

[[materials]]
name = "Material-2"
category = "Elastic"
type = "Isotropic"
data = [1.0e5, 0.25]

[[sections]]
name = "Section-1"
category = "Solid"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["rectangle"]
material_name = "Material-1"
data = []

[[outputs]]
type = "vtk"
on_screen = false

[[outputs]]
type = "text"
on_screen = false
