title = "Job-1"

[mesh]
type = "abaqus"
file = "hex8.inp"

[dof]
names = ["u1", "u2", "u3"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['Set-X0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['Set-Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u3"]
node_sets = ['Set-Z0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["u3"]
node_sets = ['Set-Z1']
element_sets = []
value = 0.002

[solver]
type = "NonlinearSolver"
option = "NewtonRaphson"
total_time = 1.0
start_time = 0.0
max_increment = 1000000
initial_dtime = 0.1
max_dtime = 0.01
min_dtime = 0.0001

[[materials]]
name = "Material-1"
category = "Plastic"
type = "IsotropicHardening"
[materials.data_dict]
E = 210000.0
nu = 0.3
yield_stress_vs_eqpl = [
    [200.0, 1000, 2000.0], # 屈服应力
    [0.0, 0.5, 1.0]  # 对应的等效塑性应变
]


[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "Solid"
type = "Volume"
option = "SmallStrain"
element_sets = ["Set-All"]
material_names = ["Material-1"]
data = []

[[outputs]]
type = "hdf5"
field_outputs = ["E", "S", "E33", "S33"]
is_save = true
