title = "Job-1"

[mesh]
type = "abaqus"
file = "rectangle_hole_quad4.inp"

[dof]
names = ["u1", "u2", "phi", "C"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['Set-Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['Set-X0Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['Set-Y1']
element_sets = []
value = 0.2

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["C"]
node_sets = ['Set-Hole']
element_sets = []
value = 1.0

[solver]
type = "NonlinearSolver"
option = "NR"
total_time = 1000
start_time = 0.0
max_increment = 1000000
initial_dtime = 100
max_dtime = 100
min_dtime = 1

[[materials]]
name = "Material-1"
category = "Elastic"
type = "Isotropic"
data = [1.0e5, 0.25]

#[[materials]]
#name = "Material-1"
#category = "Plastic"
#type = "KinematicHardening"
#data = [100000.0, 0.25, 400.0, 1000.0]

[[materials]]
name = "Material-2"
category = "PhaseField"
type = "Damage"
data = [1.0, 0.01]

[[materials]]
name = "Material-3"
category = "Diffusion"
type = "Isotropic"
data = [1.0]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [100.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "SolidPhaseDamageDiffusion"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["Set-All"]
material_names = ["Material-1", "Material-2", "Material-3"]
data = []

[[outputs]]
type = "hdf5"
field_outputs = ['S11', 'S22', 'S12', 'E11', 'E22', 'E12']
is_save = true
