title = "Job-1"

[mesh]
type = "abaqus"
file = "rectangle_hole_quad4.inp"

[dof]
names = ["u1", "u2", "phi", "C"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['SET-Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['SET-X1']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['SET-Y1']
element_sets = []
value = 0.1

#[[bcs]]
#name = "BC-3"
#category = "NeumannBC"
#type = "Concentrated"
#dof = ["u2"]
#node_sets = ['Set-Y1']
#element_sets = []
#value = 50.0

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["C"]
node_sets = ['SET-HOLE']
element_sets = []
value = 1.0
amplitude_name = "Amp-1"

[solver]
type = "NonlinearSolver"
option = "NR"
total_time = 200
start_time = 0.0
max_increment = 1000000
initial_dtime = 5
max_dtime = 5
min_dtime = 1

#[[materials]]
#name = "Material-1"
#category = "Elastic"
#type = "Isotropic"
#data = [1.0e5, 0.25]

[[materials]]
name = "Material-1"
category = "Plastic"
type = "KinematicHardening"
data = [100000.0, 0.25, 400.0, 1000.0]

#[[materials]]
#name = "Material-1"
#category = "Plastic"
#type = "Crystal"
#data = []
#[materials.data_dict]
#elastic = {symmetry = "isotropic", C11 = 169727.0, C12 = 104026.0, C44 = 86000.0}
#theta = 0.5
#slip_system_name = ["fcc{111}<110>"]
#c_over_a = [1.0]
#K = [120.0]
#dot_gamma_0 = [0.00025]
#p_s = [3.0]
#c_1 = [2000.0]
#c_2 = [10.0]
#r_0 = [10.0]
#b_s = [1.0]
#Q_s = [20.0]

[[materials]]
name = "Material-2"
category = "PhaseField"
type = "Damage"
data = [10.0, 0.02]

[[materials]]
name = "Material-3"
category = "Diffusion"
type = "Isotropic"
data = [0.00001]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
start = 0.0
data = [
    [0.0, 0.0],
    [100.0, 1.0],
    [1000.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "SolidPhaseDamageDiffusion"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["SET-ALL"]
material_names = ["Material-1", "Material-2", "Material-3"]
data = []
[sections.data_dict]
u_global = [1, 0, 0]
v_global = [0, 1, 0]
w_global = [0, 0, 1]
u_grain = [1, 0, 0]
v_grain = [0, 1, 0]
w_grain = [0, 0, 1]

[[outputs]]
type = "hdf5"
field_outputs = ['S11', 'S22', 'S12', 'E11', 'E22', 'E12']
is_save = true
