title = "Job-1"

[mesh]
#type = "gmsh"
#file = "rectangle4.msh"
type = "abaqus"
file = "rectangle625.inp"

[dof]
names = ["C"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["C"]
node_sets = ['SET-X0', 'SET-X1', 'NSET-Y0', 'NSET-Y1']
#node_sets = ['SET-X0', 'SET-X1']
element_sets = []
value = 5.0
amplitude_name = "Amp-1"

#[[bcs]]
#name = "BC-2"
#category = "DirichletBC"
#type = ""
#dof = ["C"]
#node_sets = ['SET-X1']
#element_sets = []
#value = 1.0

[solver]
#type = "LinearSolver"
type = "NonlinearSolver"
option = "NewtonRaphson"
total_time = 10.0
start_time = 0.0
max_increment = 1000000
initial_dtime = 0.5
max_dtime = 0.5
min_dtime = 0.5

[[materials]]
name = "Material-1"
category = "Diffusion"
type = "Isotropic"
data = [0.1]


[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
start = 0.0
data = [
    [0.0, 0.0],
    [1.0, 1.0],
    [10.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "Diffusion"
type = ""
option = ""
element_sets = ["SET-ALL"]
material_names = ["Material-1"]
data = []

[[outputs]]
type = "hdf5"
field_outputs = ["CFL1", "CFL2"]
is_save = true
