title = "Job-1"

[mesh]
type = "abaqus"
file = "hex20.inp"

[dof]
names = ["u1", "u2", "u3"]
order = 1
family = "LAGRANGE"

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
start = 0.0
data = [
    [0.0, 0.0],
    [0.5, 1.0],
    [1.0, 0.0],
    [1.5, -1.0],
    [2.0, 0.0],
    [2.5, 1.0],
    [3.0, 0.0],
    [3.5, -1.0],
    [4.0, 0.0],
    [4.5, 1.0],
    [5.0, 0.0],
]

[[amplitudes]]
name = "Amp-2"
type = "TabularAmplitude"
start = 0.0
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['Set-X0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ['Set-Y0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u3"]
node_sets = ['Set-Z0']
element_sets = []
value = 0.0

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ['Set-X1']
element_sets = []
value = 0.02
amplitude_name = "Amp-1"

[solver]
type = "NonlinearSolver"
option = "NewtonRaphson"
total_time = 2.0
start_time = 0.0
max_increment = 1000000
initial_dtime = 0.02
max_dtime = 0.02
min_dtime = 0.00001

[[materials]]
name = "Material-1"
category = "Plastic"
type = "CrystalGNDs"
data = [100000.0, 0.25, 400.0, 1000.0]

[[sections]]
name = "Section-1"
category = "Solid"
type = "Volume"
option = "SmallStrain"
element_sets = ["Set-All"]
material_names = ["Material-1"]
data = []

[[outputs]]
type = "vtk"
field_outputs = ['S11', 'S22', 'S33', 'S12','S13','S23', 'E11', 'E22', 'E33', 'E12', 'E13', 'E23']
on_screen = false
