title = "Job-1"

parameter_filename = "parameters.toml"

[mesh]
type = "abaqus"
file = "<INP>"

[dof]
names = ["u1", "u2", "phi"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ["Set-Y0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ["Set-Y1"]
element_sets = []
value = "<DISPY>"

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ["Set-X0-TOP"]
element_sets = []
value = "<DISPX>"

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ["Set-X1-BOTTOM"]
element_sets = []
value = 0.0

[solver]
type = "NonlinearSolver"
option = "NR"
total_time = "<TIME>"
start_time = 0.0
max_increment = 1000000
initial_dtime = "<INTERVAL>"
max_dtime = "<INTERVAL>"
min_dtime = 1e-9

[[materials]]
name = "Material-Elastic"
category = "Elastic"
type = "Isotropic"
data = [1.0e5, 0.25]

[[materials]]
name = "Material-Plastic"
category = "Plastic"
type = "KinematicHardening"
data = [100000.0, 0.25, 400.0, 1000.0]

[[materials]]
name = "Material-Phase"
category = "GradientPhaseField"
type = "Damage"
data = ["<GIC>", "<GIIC>", "<LC>"]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "SolidGradientPhaseDamage"
type = "PlaneStrain"
option = "SmallStrain"
element_sets = ["Set-All"]
material_names = ["<MAT-BULK>", "<MAT-PHASE>"]
data = []

[[outputs]]
type = "vtk"
field_outputs = ["E", "S", "S11", "S22", "S12", "E11", "E22", "E12", "Energy"]
is_save = true
