title = "Job-1"

[mesh]
type = "abaqus"
file = "hex20.inp"

[dof]
names = ["u1", "u2", "u3"]
order = 1
family = "LAGRANGE"

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
start = 0.0
data = [
    [0.0, 0.0],
    [0.5, 1.0],
    [1.0, 0.0],
    [1.5, -1.0],
    [2.0, 0.0],
    [2.5, 1.0],
    [3.0, 0.0],
    [3.5, -1.0],
    [4.0, 0.0],
    [4.5, 1.0],
    [5.0, 0.0],
]

[[amplitudes]]
name = "Amp-2"
type = "TabularAmplitude"
start = 0.0
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ["Set-X0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ["Set-Y0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-3"
category = "DirichletBC"
type = ""
dof = ["u3"]
node_sets = ["Set-Z0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-4"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ["Set-X1"]
element_sets = []
value = 0.01
amplitude_name = "Amp-1"

[solver]
type = "NonlinearSolver"
option = "NewtonRaphson"
total_time = 2.0
start_time = 0.0
max_increment = 1000000
initial_dtime = 0.1
max_dtime = 0.1
min_dtime = 0.00001

[[materials]]
name = "Material-1"
category = "Plastic"
type = "Crystal"
data = []
[materials.data_dict]
elastic = {symmetry = "isotropic", C11 = 169727.0, C12 = 104026.0, C44 = 86000.0}
theta = 0.5
slip_system_name = ["fcc{111}<110>"]
c_over_a = [1.0]
K = [120.0]
dot_gamma_0 = [0.00025]
p_s = [3.0]
c_1 = [2000.0]
c_2 = [10.0]
r_0 = [10.0]
b_s = [1.0]
Q_s = [20.0]

[[sections]]
name = "Section-1"
category = "Solid"
type = "Volume"
option = "SmallStrain"
element_sets = ["Set-All"]
material_names = ["Material-1"]
data = []
[sections.data_dict]
u_global = [1, 0, 0]
v_global = [0, 1, 0]
w_global = [0, 0, 1]
u_grain = [1, 0, 0]
v_grain = [0, 1, 0]
w_grain = [0, 0, 1]

[[outputs]]
type = "vtk"
field_outputs = ["S11", "S22", "S33", "S12","S13","S23", "E11", "E22", "E33", "E12", "E13", "E23"]
is_save = true
